src/domain/permissions.js, src/domain/permissions.spec.js
=> Add missing permission

src/components/cdn-file-picker.jsx, src/components/repository-browser.jsx
=> Enable file selection with double click

src/bundles/users.js, src/components/pages/users.jsx, src/components/pages/users.less, src/components/user-locked-out-state-editor.jsx, src/components/user-role-tag-editor.jsx, src/domain/permissions.js, src/elmu-server.js, src/services/user-api-client.js, src/services/user-service.js, src/stores/store-base.js, src/styles/main.less, src/ui/default-prop-types.js
=> Add page for user administration

src/services/document-service.js
=> Show all docs on docs page

src/components/section-editor.jsx
=> Open sections on edit page initially in edit mode

package.json, src/components/repository-browser.jsx, src/components/repository-browser.less, yarn.lock
=> Enable filtering in repository browser

src/components/pages/complete-password-reset.jsx, src/components/pages/complete-registration.jsx, src/services/mail-service.js
=> Change texts for user messages

src/plugins/ear-training/display/ear-training-display.jsx, src/plugins/ear-training/editing/ear-training-editor.jsx
=> Fix some bugs in ear training plugin

src/components/pages/edit-doc.jsx, src/components/section-editor.jsx, src/plugins/editor-factory.js, src/plugins/iframe/display/iframe-display.jsx, src/plugins/iframe/editing/iframe-editor.jsx, src/plugins/iframe/editor.js, src/plugins/iframe/iframe.less, src/plugins/iframe/renderer.js, src/plugins/plugin-infos.js, src/plugins/renderer-factory.js, src/styles/main.less, src/styles/panel.less
=> Add iframe plugin

src/components/pages/docs.jsx, src/server/client-data-mapper.js, src/server/document-controller.js, src/services/document-service.js, src/services/document-service.spec.js
=> Add cloning feature

.eslintrc, src/plugins/audio/editing/audio-editor.jsx, src/plugins/iframe/editing/iframe-editor.jsx, src/plugins/image-tiles/editing/tile-editor.jsx, src/plugins/image/editing/image-editor.jsx, src/plugins/video/editing/video-editor.jsx, src/ui/validation.js
=> Add validation feedback for insecure external links

src/components/pages/menu.js, src/components/pages/menu.less
=> Fix menu page content padding

src/repositories/cdn.js
=> Fix content type for uploads

src/components/pages/edit-doc.js, src/components/section-editor.js, src/plugins/abc-notation/info.js, src/plugins/anavis/info.js, src/plugins/annotation/info.js, src/plugins/audio/info.js, src/plugins/diagram-net/info.js, src/plugins/ear-training/info.js, src/plugins/h5p-player/info.js, src/plugins/iframe/info.js, src/plugins/image-tiles/info.js, src/plugins/image/info.js, src/plugins/interval-trainer/info.js, src/plugins/markdown/info.js, src/plugins/quick-tester/info.js, src/plugins/video/info.js, src/resources/common.yml
=> Add functionality to clone sections

src/components/doc-view.js, src/components/section-display.js
=> Add data attributes for document and section keys

src/components/pages/complete-password-reset.js, src/components/pages/complete-password-reset.less, src/components/pages/complete-password-reset.yml, src/server/user-controller.js
=> ELMU #171 Inform about invalid password reset confirmation code

test/test-users.json
Closes #187 
Add `admin` test user for consistency with the other environments and local testing of migrations
=> ELMU #187 Simplify test users and add admin

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-43
=> EDU-43 Enable archiving

package.json, yarn.lock
Resolves: https://educandu.atlassian.net/jira/software/projects/EDU/boards/1?selectedIssue=EDU-56
=> EDU-56 Update to use educandu 03a44df72fe

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-83
=> EDU-83 Bump educandu to version after EDU-71

package.json, src/bundles/edit-bundle.js, yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-127
=> EDU-127 Update educandu

package.json, src/index.js, src/polyfills.js, yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-130
=> EDU-130 Update educandu

gulpfile.js
Closes https://educandu.atlassian.net/browse/EDU-133
=> EDU-133 Await for child process to gracefully shut down

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-2
=> ELMU-2 Update educandu

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-4
=> ELMU-4 Update educandu

.github/workflows/ci.yml, Dockerfile, package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-6
=> ELMU-6 Update node.js version to latest

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-8
=> ELMU-8 Update educandu

package.json, src/articles-controller.js, src/index.js, yarn.lock
Closes: https://educandu.atlassian.net/browse/ELMU-9
=> ELMU-9 Update educandu and introduce an articles controller

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-10
=> ELMU-10 Update educandu

package.json, yarn.lock
Closes: https://educandu.atlassian.net/browse/ELMU-11
=> ELMU-11 Update educandu

gulpfile.js
Closes https://educandu.atlassian.net/browse/ELMU-12
=> ELMU-12 Wait for child process to exit when stopping gulp

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-13
=> ELMU-13 Update to educandu v0.6.0

package.json, src/bundles/page-template.js, src/bundles/page-template.less, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-21
=> ELMU-21 Update educandu to v0.7.2

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-22
=> ELMU-22 Update educandu to v0.7.3

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-23
=> ELMU-23 Update educandu to v0.7.4

package.json, src/bundles/page-template.js, src/bundles/page-template.less, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-24
=> ELMU-24 Update educandu to v0.8.0

package.json, yarn.lock
Closes: https://educandu.atlassian.net/browse/ELMU-27
=> ELMU-27 Update to educandu v0.10.0

gulpfile.js, package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-28
=> ELMU-28 Update educandu to v0.11.0

package.json, src/bundles/page-template.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-30
=> ELMU-30 Update educandu to v0.12.0 and adjust page template accordingly

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-31
=> ELMU-31 Update educandu to v0.13.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-33
=> Update educandu to v0.15.1

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-34
=> ELMU-34 Update educandu to v0.15.2

package.json, src/bundles/page-template.less, src/bundles/site-logo.less, src/main.less, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-36
=> ELMU-36 Update educandu to v0.17.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-37
=> ELMU-37 Update educandu to v0.17.1

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-38
=> ELMU-38 Update educandu to v0.18.0

package.json, src/bundles/page-template.js, src/bundles/page-template.less, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-39
=> ELMU-39 Update educandu to v0.19.1

package.json, src/bundles/page-template.js, src/bundles/page-template.less, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-40
=> ELMU-40 Update educandu to v0.20.0

package.json, src/bundles/page-template.js, src/bundles/page-template.less, src/main.less, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-41
=> ELMU-41 Update educandu to v0.21.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-42
=> ELMU-42 Update educandu to v0.22.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-44
=> ELMU-44 Update educandu to v0.23.2

package.json, src/bundles/bundle-config.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-48
=> ELMU-48 Update educandu to v0.25.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-50
=> ELMU-50 Update educandu to v0.26.1

package.json, src/bundles/bundle-config.js, src/bundles/home-page-template.js, src/bundles/home-page-template.less, src/bundles/page-footer.js, src/bundles/page-footer.less, src/bundles/page-header.js, src/bundles/page-header.less, src/bundles/page-template.less, src/main.less, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-51
=> ELMU-51 Update educandu to v0.27.0

package.json, src/main.less, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-54
=> ELMU-54 Update educandu to v0.29.0

package.json, src/bundles/page-header.js, src/bundles/site-logo.less, src/main.less, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-55
=> ELMU-55 Update educandu to v0.30.1

package.json, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-56
=> ELMU-56 Update educandu to v0.31.1

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-58
=> ELMU-58 Update educandu to v0.32.0

package.json, src/bundles/page-header.js, src/resource-overrides.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-57
=> ELMU-57 Update educandu to v0.33.0

gulpfile.js, package.json, src/bundles/home-page-template.js, src/bundles/page-template.js, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-59
=> ELMU-59 Update educandu to v0.34.1

package.json, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-61
=> ELMU-61 Update educandu to v0.34.3

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-62
=> ELMU-62 Update educandu to v0.35.0

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-63
=> ELMU-63 Update educandu to v0.36.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-64
=> ELMU-64 Update educandu to v0.37.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-65
=> ELMU-65 Update educandu to v0.38.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-66
=> ELMU-66 Update educandu to 0.39.2

package.json, src/bundles/page-footer.js, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-67
=> ELMU-67 Update educandu to v0.40.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-68
=> ELMU-68 Update educandu to v0.41.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-69
=> ELMU-69 Update educandu to v0.42.0

gulpfile.js, package.json, src/bundles/page-header.js, src/main.less, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-71
=> ELMU-71 Update educandu to v0.44.0

package.json, src/articles-controller.js, src/bundles/page-footer.js, src/bundles/page-header.js, src/bundles/site-logo.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-73
=> ELMU-73 Update educandu to v0.46.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-74
=> ELMU-74 Update educandu to v0.47.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-75
=> ELMU-75 Update educandu to v0.48.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-76
=> ELMU-76 Update educandu to v0.49.0

package.json, src/bundles/page-header.js, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-77
=> ELMU-77 Update educandu to v0.50.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-78
=> ELMU-78 Update educandu to v0.51.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-79
=> ELMU-79 Update educandu to v0.52.1

package.json, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-80
=> ELMU-80 Update educandu to v0.53.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-81
=> ELMU-81 Update educandu to v0.54.0

package.json, src/polyfills.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-82
=> ELMU-82 Update educandu to v0.55.0

package.json, src/bundles/page-footer.js, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-83
=> ELMU-83 Update educandu to v0.56.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-84
=> ELMU-84 Update educandu to v0.57.0

package.json, src/articles-controller.js, yarn.lock
Almost swiftly closes https://educandu.atlassian.net/browse/ELMU-85
=> ELMU-85 Update educandu to v0.58.1

gulpfile.js, package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-86
=> ELMU-86 Update educandu to v0.59.0

src/resource-overrides.json
Closes https://educandu.atlassian.net/browse/ELMU-87
=> ELMU-87 Fix registration and password reset emails

package.json, src/resource-overrides.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-88
=> ELMU-88 Update educandu to v0.60.0

gulpfile.js, package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-90
=> ELMU-90 Update educandu to v0.61.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-89
=> ELMU-89 Update dev-tools to v3.0.1

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-91
=> ELMU-91 Update educandu to v0.62.0

package.json, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-92
=> ELMU-92 Update educandu to v0.63.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-93
=> ELMU-93 Update educandu to v0.64.0

gulpfile.js, package.json, src/bundles/page-header.less, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-94
=> ELMU-94 Update educandu to v0.65.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-95
=> ELMU-95 Update educandu to v0.65.1

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-96
=> ELMU-96 Update educandu to v0.66.0

package.json, src/resource-overrides.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-97
=> ELMU-97 Update educandu to v0.67.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-98
=> ELMU-98 Update educandu to v0.68.0

gulpfile.js, package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-100
=> ELMU-100 Update educandu to v0.70.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-101
=> ELMU-101 Update educandu to v0.71.0

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-102
=> ELMU-102 Update educandu to v0.72.0

gulpfile.js, src/index.js
Closes https://educandu.atlassian.net/browse/ELMU-103
=> ELMU-103 Include music-xml-viewer plugin

gulpfile.js, package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-105
=> ELMU-105 Update educandu to v0.72.1

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-106
=> ELMU-106 Update educandu to v0.73.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-107
=> ELMU-107 Update educandu to v0.74.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/ELMU-108
=> ELMU-108 Update educandu to v0.75.0
